name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      env:
        RUSTFLAGS: "-Dwarnings"
      run: cargo build --locked

    - name: Run tests
      env:
        RUSTFLAGS: "-Dwarnings"
      run: cargo test --locked

    - name: Run Clippy
      env:
        RUSTFLAGS: "-Dwarnings"
      run: cargo clippy --locked

    - name: Check formatting
      run: cargo fmt --check
